### ISSUE TITLE
ema更新

### ISSUE THREAD

**Issue by xiaodaobuzhi** [Aitical/Task-agnostic_Model_Contrastive_Learning_Image_Restoration#3]
负模型的更新是指在模型权重上进行加权融合吗？还是负模型的生成样本上进行加权融合

**Comment by Aitical** [comment]
EMA是对负模型权重进行更新
```
for p_neg, p in zip(model_neg.parameters(), model.parameters()):
    p_neg.data = w*p_neg.data + (1-w)*p.data
```
也可以参考BasicSR中的实现
https://github.com/XPixelGroup/BasicSR/blob/033cd6896d898fdd3dcda32e3102a792efa1b8f4/basicsr/models/base_model.py#L75
